### ISSUE TITLE
Take inputs from function arguments rather than using prompts

### ISSUE THREAD

**Issue by kasipavankumar** [jscrates/packages#3]
@Jarvis2001

Please make the following changes:
- Take inputs from function arguments rather than using prompt or hardcoded values.

For example in the following code snippet:
https://github.com/jscrates/packages/blob/d2c9528157c42f09c23313cfec41fdf8742584ae/packages/factorial/factorial.js#L3

**Comment by Jarvis2001** [comment]
Done

**Comment by Jarvis2001** [comment]
Now?
